### ISSUE TITLE
Vulcrane is missing from the Dataset

### ISSUE THREAD

**Issue by 40Cakes** [BLinssen/TemTacO#2]
Hi, I'm currently trying out this app, unfortunately I cannot get it to work...

I noticed Vulcrane is missing from the Dataset which is causing the HUD to not work for me :(
I can't seem to get it working when I add my own 150x35 image to the Dataset folder...

Here is a 3440x1440 image of a battle with my Vulcrane in it: https://i.imgur.com/Y4g3yjG.jpg
And a 1920x1080: https://i.imgur.com/b4QPoUs.png

Hope this helps! Good luck with the project, it looks awesome so far!
Unrelated, are those black bars on the left & right edge of the window normal?

**Comment by BLinssen** [comment]
Hey, in v0.4.1 your resolution has been added, there is also no more need for the dataset. Thanks for the picture though, it helps with added a new resolution.

The black bars I'm not sure about.

**Comment by 40Cakes** [comment]
Thank you for the quick fix, appreciate it! 👍
