### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by lchamp** [BLinssen/TemTacO#5]
Hello @BLinssen,

I've just learned about your overlay TemTacO.
Would it be possible to: 

1. Provide an update for new update of the game (with new temtems)?
2. Maybe use the available pull request too (fraction instead of decimals and shows types)?

Thanks!

**Comment by Tecnoknight5** [comment]
You can manually update the text file with the new temtems until this gets updated.

**Comment by BLinssen** [comment]
I've added the Fraction pull request, updated the new Temtems (as far as I could find on the Wiki) and made some improvements to the Trait Display. You can find it in release 4.2 (https://github.com/BLinssen/TemTacO/releases/tag/v0.4.2)
