### ISSUE TITLE
Decimals are still shown instead of fractions

### ISSUE THREAD

**Issue by lchamp** [BLinssen/TemTacO#6]
Hello @BLinssen, @icampbe,

Related to : [this](https://github.com/BLinssen/TemTacO/pull/4/commits/78084bdcf8098cb09a229a81cfe378f2c29939c8) pull request
Expectation : values should be shown as fraction, such as "½" and "¼"
Reality : values are still shown as decimals, such as ",5" and ",25".
Screenshot : https://i.imgur.com/r4Dg1fI.jpg

I don't have the required tools to (try to) make my own fix and the PR for it but I suspect :

In file _MainWindow.xaml.cs_
`if (str.Equals(".5"))` and `if (str.Equals(".25"))`
needs to become
`if (str.Equals(".5") || str.Equals(",5"))` and `if (str.Equals(".25") || str.Equals(",25"))`
because depending on the locale the decimals are shown with a comma (like myself) or a dot.

Thanks in advance for your help and upcoming fix release 👍

**Comment by BLinssen** [comment]
I've made the change you requested and added it into the release (and uploaded a new Zip file)
Feel free to try it out with your locale and hopefully it'll do the trick

**Comment by lchamp** [comment]
I can confirm, it works now!

Screenshot 1 : https://i.imgur.com/Mvd7Ml1.jpg
Screenshot 2 : https://i.imgur.com/AhHl6ub.jpg

Thanks 👍
